version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3-management
    # restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/11-custom.conf
      - ./definitions.json:/opt/definitions.json
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    # networks:
    #   appnet:
    #     aliases:
    #       - rabbit
    deploy:
      replicas: 1
  adminer:
      image: adminer
      ports:
        - 8080:8080
