# Use root/example as user/password credentials
version: '3.3'

services:

  mongo:
    image: mongo:4.2
    networks:
      appnet:
        aliases:
          - mongo
    secrets:
      - db_dba_password
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 100
    depends_on:
      - mongo
    secrets:
      - db_dba_password
    ports:
      - 8081:8081
      - 80:80
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: 	mongodb://root:example@mongo:27017
      # ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_SERVER: mong
      # ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      # ME_CONFIG_BASICAUTH_USERNAME: guest
      # ME_CONFIG_BASICAUTH_PASSWORD: guest
    networks:
      - appnet
secrets:
  db_dba_password:
    external: true


networks:
  appnet:
    external: true