# Use root/example as user/password credentials
version: '3.3'

services:

  mongo:
    image: mongo
    networks:
      - appnet
    secrets:
      - db_dba_password
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    secrets:
      - db_dba_password
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      appnet:
        aliases:
          - mymongo
secrets:
  db_dba_password:
    external: true


networks:
  appnet:
    external: true