version: '3.9'

services:
  unl1_agent:
    image: agent_service:latest
    networks:
      core_network:
        aliases:
          - unl1_agent
      unl_1:
        aliases:
          - unl1_agent
    environment:
      AMQ_PASSWORD_FILE: /run/secrets/rabbitmq_user
      AMQ_USER: normal_user
      HOSTNAME: unl1_agent
    secrets:
      - rabbitmq_user
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - service_logs:/var/log/service_logs
      - /Users/jorrit/Documents/master-software-engineering/thesis/swarm_setup/stack/:/var/log/stack-files
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == worker
      #     - node.labels.server == agent1

  unl2_agent:
    image: agent_service:latest
    networks:
      core_network:
        aliases:
          - unl2_agent
      unl_2:
        aliases:
          - unl2_agent
    environment:
      INPUT_QUEUE: core_queue_agent
      AMQ_PASSWORD_FILE: /run/secrets/rabbitmq_user
      AMQ_USER: normal_user
      HOSTNAME: unl2_agent
    secrets:
      - rabbitmq_user
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - service_logs:/var/log/service_logs
      - /Users/jorrit/Documents/master-software-engineering/thesis/swarm_setup/stack/:/var/log/stack-files
    deploy:
      replicas: 1
  #     # placement:
  #     #   constraints:
  #     #     - node.role == worker
  #     #     - node.labels.server == agent1


secrets:
  rabbitmq_user:
    external: true

networks:
  core_network:
    external: true
  unl_1:
    external: true
  unl_2:
    external: true
  third_party:
    external: true

volumes:
  service_logs:
    external: true