version: '3.9'

services:
  agent:
    image: agent_service:latest
    networks:
      core_network:
        aliases:
          - agent1
      # appnet:
      #   aliases:
      #     - agent1
    environment:
      INPUT_QUEUE: core_queue_agent1
      AMQ_PASSWORD_FILE: /run/secrets/rabbitmq_user
      AMQ_USER: normal_user
    secrets:
      - rabbitmq_user
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - service_logs:/var/log/service_logs
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == worker
      #     - node.labels.server == agent1


secrets:
  rabbitmq_user:
    external: true

networks:
  core_network:
    external: true
  appnet:
    external: true

volumes:
  service_logs:
    external: true