version: '3.9'

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.1
    hostname: etcd1
    networks:
      core_network:
        aliases:
          - etcd1
    ports:
      - 2379:2379
    command:
      - /usr/local/bin/etcd
      - --name=etcd1
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd1:2379
      - --initial-cluster-token=my-etcd-token
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new

  etcd2:
    image: quay.io/coreos/etcd:v3.5.1
    hostname: etcd2
    networks:
      core_network:
        aliases:
          - etcd2
    command:
      - /usr/local/bin/etcd
      - --name=etcd2
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd2:2379
      - --initial-cluster-token=my-etcd-token
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new

  etcd3:
    image: quay.io/coreos/etcd:v3.5.1
    hostname: etcd3
    networks:
      core_network:
        aliases:
          - etcd3
    command:
      - /usr/local/bin/etcd
      - --name=etcd3
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd3:2379
      - --initial-cluster-token=my-etcd-token
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/11-custom.conf
      - ./definitions.json:/opt/definitions.json
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_LOGS: "-"
    networks:
      core_network:
        aliases:
          - rabbit
      unl_1:
        aliases:
          - rabbit
      unl_2:
        aliases:
          - rabbit
      third_party:
        aliases:
          - rabbit
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  # zipkin:
  #   image: openzipkin/zipkin:2.24.0
  #   ports:
  #     - 9411:9411
  #   networks:
  #     core_network:
  #       aliases:
  #         - zipkin

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      # - /var/log/thesis_logs/loki-data:/loki
      # - ./loki-index:/loki/index
      # - ./loki-chunks:/loki/chunks
    networks:
      core_network:
        aliases:
          - loki

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - service_logs:/var/log/service_logs
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      core_network:
        aliases:
          - promtail

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      core_network:
        aliases:
          - grafana
  db:
    image: mysql
    secrets:
      - db_root_password
      - db_dba_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_dba_password
    networks:
      unl_1:
        aliases:
          - mysql
      unl_2:
        aliases:
          - mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/jorrit/Documents/master-software-engineering/thesis/swarm_setup/db/:/docker-entrypoint-initdb.d
      - type: bind
        source: /Users/jorrit/Documents/mysql
        target: /var/lib/mysql

networks:
  core_network:
    external: true
  unl_1:
    external: true
  unl_2:
    external: true
  third_party:
    external: true

volumes:
  service_logs:
    external: true


secrets:
  db_root_password:
    external: true
  db_dba_password:
    external: true
